### ISSUE TITLE
Depression Description 

### ISSUE THREAD

**Issue by jbesraa** [CYPIAPT-LNDSE/sdm-app#24]
Hi @rosatown,

We are planing to write a little description about depression in the application.
here is what we came up with: 

"We all feel fed up, miserable or sad at times. These feelings don't usually last longer than a week, and they don't interfere too much with our lives. Sometimes there's a reason, sometimes not. We usually cope.
However, in Depression:
Your feelings don't lift after a few days, they carry on for weeks or more and even interfere with your life."

if you have any comments about it, let us know please (:

**Comment by rosatown** [comment]
Hi guys, here's a slightly edited version of this one:

Everyone can feel fed up, hopeless, miserable or sad at times. Sometimes there's a reason, sometimes not. If you're finding that your feelings are keeping you from getting on with your life, it may be good to find out about the different treatment and support options that are out there for feeling depressed.

**Comment by jbesraa** [comment]
great.
thanks @rosatown
