### ISSUE TITLE
user story 

### ISSUE THREAD

**Issue by jbesraa** [CYPIAPT-LNDSE/sdm-app#3]

**Comment by rosatown** [comment]
Remind me what we are supposed to do here? I feel like you asked us to come up with a user story...

**Comment by njsfield** [comment]
Sorry for the delay Rosa! Originally, User Stories were going to be added here on Saturday, but as we hadn't had time this issue had been left open.

We are now adding the User Stories (which you should be able to see on the main README page) to separate issues here.

**Comment by rosatown** [comment]
No worries, Nick. ☺

Best wishes,

Rosa

**Comment by njsfield** [comment]
@rosatown, @DHayes1987 also, we'd like to present you with two solutions on Thursday to help satisfy this User Story;

> As a young person suffering from depression,
I would like be able to navigate the App myself,
so I can easily explore the options for my treatment.

## Solutions
1. Will be a question/answer based guide, very similar to the App solution we created on Saturday together.
2. Will be an interactive animation for a young person to go through, that will present them with how a journey might look if they choose one of the three support options (Practical, Talking or Medication) as a solution for getting help with depression. This is meant to be colourful, delightful to view and interesting for a child to interact with, so they aren't just presented with the question/answer based guide.

We'd like to create the homepage in a way that lets the user choose one of these two options (perhaps a button for *interactive*, and a button for *guide*). 

Would you be okay if we presented you these two solutions?

**Comment by rosatown** [comment]
Yes please. We look forward to seeing them!
